# https://www.psychologytoday.com/intl/blog/the-future-brain/201901/ai-created-in-dna-based-artificial-neural-networks
# https://tincture.io/when-ai-meets-dna-dd9a212fc825
# https://www.technologies.org/?p=3675
# https://www.quantamagazine.org/artificial-intelligence-finds-ancient-ghosts-in-modern-dna-20190207/
# https://www.forbes.com/sites/bernardmarr/2018/11/16/the-amazing-ways-artificial-intelligence-is-transforming-genomics-and-gene-editing/#496b56ae42c1
# https://tlo.mit.edu/technologies/artificial-intelligence-dna-analysis-software
# https://www.vice.com/en_us/article/594mvz/ai-made-from-human-dna
# https://www.wired.com/story/google-is-giving-away-ai-that-can-build-your-genome-sequence/
# https://emerj.com/ai-sector-overviews/machine-learning-in-genomics-applications/
# https://www.alphr.com/artificial-intelligence/1010248/ai-successfully-predict-changes-in-dna
# https://blog.floydhub.com/exploring-dna-with-deep-learning/
# https://towardsdatascience.com/deep-learning-on-ancient-dna-df042dc3c73d
# https://www.nature.com/articles/s41588-018-0328-0
# https://www.kaggle.com/thomasnelson/working-with-dna-sequence-data-for-ml
